// Copyright 2020-2023 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

fn main() {
  let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
  if target_os == "macos" || target_os == "ios" {
    println!("cargo:rustc-link-lib=framework=WebKit");

    println!("cargo:rerun-if-env-changed=WRY_OBJC_SUFFIX");
    set_objc_source_id_env();
  }

  if target_os == "android" {
    use std::{fs, path::PathBuf};

    fn env_var(var: &str) -> String {
      std::env::var(var).unwrap_or_else(|_| {
        panic!("`{var}` is not set, which is needed to generate the kotlin files for android.")
      })
    }

    println!("cargo:rerun-if-env-changed=WRY_ANDROID_PACKAGE");
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_LIBRARY");
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR");

    if let Ok(kotlin_out_dir) = std::env::var("WRY_ANDROID_KOTLIN_FILES_OUT_DIR") {
      let package = env_var("WRY_ANDROID_PACKAGE");
      let library = env_var("WRY_ANDROID_LIBRARY");

      let kotlin_out_dir = PathBuf::from(&kotlin_out_dir)
        .canonicalize()
        .unwrap_or_else(move |_| {
          panic!("Failed to canonicalize `WRY_ANDROID_KOTLIN_FILES_OUT_DIR` path {kotlin_out_dir}")
        });

      let kotlin_files_path =
        PathBuf::from(env_var("CARGO_MANIFEST_DIR")).join("src/android/kotlin");
      println!("cargo:rerun-if-changed={}", kotlin_files_path.display());
      let kotlin_files = fs::read_dir(kotlin_files_path).expect("failed to read kotlin directory");

      for file in kotlin_files {
        let file = file.unwrap();

        let class_extension_env = format!(
          "WRY_{}_CLASS_EXTENSION",
          file
            .path()
            .file_stem()
            .unwrap()
            .to_string_lossy()
            .to_uppercase()
        );
        let class_init_env = format!(
          "WRY_{}_CLASS_INIT",
          file
            .path()
            .file_stem()
            .unwrap()
            .to_string_lossy()
            .to_uppercase()
        );

        println!("cargo:rerun-if-env-changed={class_extension_env}");
        println!("cargo:rerun-if-env-changed={class_init_env}");

        let content = fs::read_to_string(file.path())
          .expect("failed to read kotlin file as string")
          .replace("{{package}}", &package)
          .replace("{{package-unescaped}}", &package.replace('`', ""))
          .replace("{{library}}", &library)
          .replace(
            "{{class-extension}}",
            &std::env::var(&class_extension_env).unwrap_or_default(),
          )
          .replace(
            "{{class-init}}",
            &std::env::var(&class_init_env).unwrap_or_default(),
          );

        let auto_generated_comment = match file
          .path()
          .extension()
          .unwrap_or_default()
          .to_str()
          .unwrap_or_default()
        {
          "pro" => "# THIS FILE IS AUTO-GENERATED. DO NOT MODIFY!!\n\n",
          "kt" => "/* THIS FILE IS AUTO-GENERATED. DO NOT MODIFY!! */\n\n",
          _ => "String::new()",
        };
        let mut out = String::from(auto_generated_comment);
        out.push_str(&content);

        let out_path = kotlin_out_dir.join(file.file_name());
        // Overwrite only if changed to not trigger rebuilds
        if fs::read_to_string(&out_path).map_or(true, |o| o != out) {
          fs::write(&out_path, out).expect("Failed to write kotlin file");
        }
        println!("cargo:rerun-if-changed={}", out_path.display());
      }
    }
  }

  let target = std::env::var("TARGET").unwrap_or_default();
  let android = target.contains("android");
  let linux = !android
    && (target.contains("linux")
      || target.contains("freebsd")
      || target.contains("dragonfly")
      || target.contains("netbsd")
      || target.contains("openbsd"));
  alias("linux", linux);
  alias("gtk", cfg!(feature = "os-webview") && linux);
}

fn alias(alias: &str, condition: bool) {
  if condition {
    println!("cargo:rustc-cfg={alias}");
  }
}

fn set_objc_source_id_env() {
  let version = std::env::var("CARGO_PKG_VERSION").unwrap();
  let source_id = std::env::var("WRY_OBJC_SUFFIX")
    .ok()
    .and_then(|suffix| sanitize_objc_source_id(&suffix))
    .or_else(git_commit_hash);

  if let Some(source_id) = source_id {
    // Audio plugin hosts can load multiple plugin dylibs into one process. If
    // two dylibs contain patched wry sources with the same crate version, the
    // Objective-C runtime sees the same objc2 autogenerated class names even
    // though their method implementations or ivar layouts may differ.
    //
    // objc2's autogenerated class names include CARGO_PKG_VERSION and, unlike
    // explicit #[name = ...] classes, intentionally allow same-name classes to
    // be reused across dylibs. Preserve that reuse for identical wry sources,
    // but add a deterministic source id so different wry commits do not share
    // Objective-C class definitions by accident.
    println!("cargo:rustc-env=CARGO_PKG_VERSION={version}+{source_id}");
  }
}

fn git_commit_hash() -> Option<String> {
  let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").ok()?;
  let output = std::process::Command::new("git")
    .args(["-C", &manifest_dir, "rev-parse", "--short=12", "HEAD"])
    .output()
    .ok()?;

  if !output.status.success() {
    return None;
  }

  let hash = String::from_utf8(output.stdout).ok()?.trim().to_owned();
  if hash.is_empty() {
    None
  } else {
    Some(hash)
  }
}

fn sanitize_objc_source_id(source_id: &str) -> Option<String> {
  let mut sanitized = String::new();
  for ch in source_id.chars() {
    if ch.is_ascii_alphanumeric() {
      sanitized.push(ch.to_ascii_lowercase());
    } else if !sanitized.ends_with('.') {
      sanitized.push('.');
    }
  }

  let sanitized = sanitized.trim_matches('.');
  if sanitized.is_empty() {
    None
  } else {
    Some(sanitized.to_owned())
  }
}
